hypervisor/openstack: fix usage with V3 API
puppetlabs/beaker-openstack pull request #5
Opened 2019-05-06 14:15 UTC by GiedriusS

KeyStone V3 API needs the project name instead of the tenant's name
(such field doesn't exist anymore). Transparently let users pass both
options. At least one needs to be specified. Later on, Fog handles
switching between the V3 and V2 versions depending on the
openstack_auth_url parameter.

Fix one issue with changed naming + bump `fog-openstack` requirement.

2019-05-06 16:43 UTC, kevpl requested changes
one small change requested in current code. Please add some spec tests to ensure we don't break your fix in the future, & we'll look to push this through testing to release!

2019-05-06 16:43 UTC, kevpl commented on lib/beaker/hypervisor/openstack.rb
> +    }.merge(extra_credentials)
this line should be intended once more to match the block it's surrounding.

2019-05-08 07:32 UTC, GiedriusS commented
Thanks for the quick review! Will definitely do that and ping you once the v2 is ready.

2019-05-08 13:07 UTC, GiedriusS commented
@kevpl PTAL if this makes sense. I have done what you've said + added another option which controls whether a floating IP should be allocated. In our OpenStack deployment we use no such feature (and we do not have any pools available) so we needed a way to disable it :smile:

2019-06-03 17:46 UTC, kevpl approved these changes
apologies on taking so long to come back to this, lgtm 👍. Let's get this through testing:

@puppetlabs-jenkins test this please

@GiedriusS, from your comment at the top, it looks like this change is backwards compatible, in that you can still use the previous version of the API (v2) without changing any of your beaker-openstack settings. Is this correct, or am I not understanding your comment at the beginning of the PR on usage? I'm looking to figure out if this change is backwards-compatible or not for our version number update on release.

2019-06-04 08:30 UTC, GiedriusS commented
From OpenStack's perspective it is not but from our perspective - it is because we can still pass the V2 parameters to `fog-openstack` and then later on it should use only V2 API calls. You can find more here:
https://docs.openstack.org/keystone/pike/contributor/http-api.html

> 
> Note a few key differences when compared to the v2.0 API:
> 
> A “tenant” in v2.0 became a “project” in v3.

`fog-openstack` supports both: https://github.com/fog/fog-openstack/tree/master/lib/fog/openstack/identity

2019-06-04 08:32 UTC, GiedriusS commented
FWIW, I have only tested the happy paths that were added in this PR. Have been using it for about a month without any problems. Can't test it with `v2` since I don't have any endpoints to play around with :smile: 

AFAICT the only non-backward compatible change is the requirement to pass the parameter `openstack_floating_ip` so there should be a new major version.

2019-06-17 16:41 UTC, kevpl commented
test this please

2019-06-17 16:47 UTC, merged

2019-06-17 17:02 UTC, kevpl commented
released as beaker-openstack [0.3.0](https://github.com/puppetlabs/beaker-openstack/compare/0.2.0...0.3.0)! Thanks for your contribution @GiedriusS!

2019-07-04 17:29 UTC, GiedriusS commented
Thanks, @kevpl, switched back to using the new upstream version here internally!